package com.codevik.socialmediaapiintegration.util.validation;

import lombok.Getter;
import org.springframework.http.HttpStatus;

/**
 * Created by Sonal on 22-09-2016.
 *
 * @formatter:off
 */


@Getter
public enum ErrorCode {

  REQUEST_ID_MISSING(18000, "Request ID is missing."),
  SOURCE_ID_MISSING(18001, "Source ID is missing."),
  FULFILLMENT_TYPE_MISSING(18002, "Fulfillment type is missing."),
  DATA_FMT_MISSING(18003, "Data format is missing."),
  REQUEST_CATG_MISSING(18004, "Request category is missing."),
  INVALID_REQUEST_CATG(18005,
      "Valid values for request category are 'BulkDataOnly', 'BulkPrintReady', 'TransactionalInlineDataOnly', 'TransactionalExternalDataOnly', 'TransactionalInlinePrintReadyMultItem', 'TransactionalInlinePrintReadySingleItem' and 'TransactionalExternalPrintReady'."),
  REQUEST_DATE_MISSING(18006, "Request date is missing."),
  REQUEST_TYPE_MISSING(18007, "Request type is missing."),
  REQUEST_ITEM_COUNT_MISSING(18008, "Request item count is missing."),
  SOURCE_ID_NOT_FOUND(18009, "Source ID is not found."),
  REQUEST_DATE_FMT_INVALID(18010, "Request date format is invalid."),
  REQUEST_TYPE_INVALID(18011, "Request type is invalid."),
  FULFILLMENT_TYPE_NOT_FOUND(18012, "Fulfillment type is not found."),
  SENDING_RULE_NOT_FOUND(18013, "Sending rule not found."),
  FILE_NAME_MISSING(18014, "File name is missing."),
  FILE_SIZE_MISSING(18015, "File size is missing."),
  RECIPIENT_TYPE_NOT_FOUND(18016, "Recipient type is not found."),
  BATCHING_RULE_NOT_FOUND(18017, "Batching rule not found."),
  PROCESSOR_ID_MISSING(18018, "Processor ID is missing."),
  PROCESSOR_ID_NOT_FOUND(18019, "Processor ID is not found."),
  REMOVE_TAG(18020, "Remove complete tag, if value not provided for optional field"),
  EVENT_TYPE_MISSING(18021, "Event type is missing."),
  EVENT_TYPE_NOT_FOUND(18022, "Event type is not found."),
  RECEIVED_DATE_MISSING(18023, "Received date is missing."),
  INVALID_RECEIVE_DATE_FMT(18024, "Received date format invalid."),
  INVALID_DISPATCH_DATE_FMT(18025, "Dispatched date format invalid."),
  EVENT_STATUS_CODE_MISSING(18026, "Event status code is missing."),
  INVALID_EVENT_STATUS_CODE(18027, "Event status code is invalid."),
  EVENT_STATUS_MSG_MISSING(18028, "Event status message missing."),

  SEARCH_START_DATE_MISSING(18051, "Search start date missing"),
  SEARCH_END_DATE_MISSING(18052, "Search end date missing"),
  SEARCH_START_DATE_INVALID(18053, "Search start date invalid"),
  SEARCH_END_DATE_INVALID(18054, "Search end date invalid"),
  INVALID_DISPATCHED_DATE(HttpStatus.BAD_REQUEST.value(), "Invalid dispatched date."),

  SUCCESS_COUNT_MISSING(18029, "Success count is missing."),
  EXCEPTION_COUNT_MISSING(18030, "Exception count is missing."),
  BULK_DATA_FILES_NOT_FOUND(18031, "Bulk data file(s) not found in landing zone."),
  INVALID_BULK_DATA_STRUCTURE(18032, "Bulk data file structure not per standard."),
  REQUEST_ITEM_COUNT_MISMATCH(18033,
      "Request item count mismatch between request and bulk data files."),
  RECIPIENT_TYPE_MANDATION(18034, "Recipient type is mandatory."),
  MESSAGE_ID_DATA_MISMATCH(18035,
      "Message identifier and descriptive data do not match fulfillment request in the database."),
  DOC_COMPOSITION_ENGINE_ID_NOT_FOUND(18036, "Document Composition Engine ID is not found."),
  PRINT_FILE_NOT_FOUND_IN_LANDING_ZONE(18037, "Print file not found in landing zone."),
  EITHER_ORGANIZATION_TYPE_OR_PERSON_TYPE(18038,
      "Only Person details or Organization details is valid; both cannot be valued for the same recipient."),
  SENDING_RULE_NOT_IN_EFFECT(18039, "Sending rule is not in effect."),
  INVALID_CANCEL_REQUEST(18040,
      "Cancel fulfillment request message does not comply with standard."),
  DUPLICATE_CANCEL_REQUEST(18041, "Duplicate cancellation request"),
  CANCELLATION_ON_INACTIVE_REQUEST(18042,
      "Cancellation action cannot be applied to an inactive request."),
  CANCELLATION_ON_HUB_REQUEST(18043,
      "Cancellation action cannot be applied to a MC-originated request."),
  CANCELLATION_ON_REJECTED_REQUEST(18044,
      "Cancellation action cannot be applied to a rejected request."),
  EITHER_DOMESTIC_OR_INTERNATIONAL_ADDRESS(18045,
      "Only domestic or international mailing address is valid; both cannot be valued for the same recipient."),
  EITHER_DOMESTIC_OR_INTERNATIONAL_RETURN_ADDRESS(18046,
      "Only domestic or international return address is valid; both cannot be valued for the same recipient."),
  SENDING_RULE_NOT_EXPIRED(18047, "Sending rule is expired."),
  EXCEPTION_CREATING_DRL_FILE(18048, "Exception creating .DRL file."),
  SEARCH_SOURCE_ID_MISSING(18049, "Search source ID missing."),
  SEARCH_SOURCE_ID_NOT_FOUND(18050, "Search source ID not found."),
  SEARCH_START_REQUEST_DATE_MISSING(18051, "Search start request date missing"),
  SEARCH_END_REQUEST_DATE_MISSING(18052, "Search end request date missing."),
  SEARCH_START_REQUEST_DATE_INVALID(18053, "Search start request date invalid."),
  SEARCH_END_REQUEST_DATE_INVALID(18054, "Search end request date invalid."),
  SEARCH_DATE_OUT_OF_RANGE(18055,
      "Search date range allowed is minimum of one day to maximum of one year."),
  REQUEST_HISTORY_MISSING(18056, "No fulfillment request history instances found."),
  RULE_SERVICE_CONNECTION_REFUSED(18057, "RulesService connection refused."),
  ERROR_IN_PARSING_DATA(18058,
      "Error occurred during parsing data fetched from DB against <CollectionName> collection"),
  ERROR_IN_DATABASE_COMMUNICATION(18059, "Error occurred during database communication"),
  DESTINATION_ID_MISSING(18060, "Destination ID is mandatory."),
  DOCUMENT_TYPE_MANDATORY(18061, "Document type is mandatory."),
  DOCUMENT_META_DATA_MISSING(18062, "No metadata name-value pair defined."),
  BUSINESS_SEGMENT_MISSING(18063, "Business segment is missing."),
  MARKET_SEGMENT_MISSING(18064, "Market segment is missing."),
  INVALID_RECIPIENT_ID(18067, "Recipient ID mismatch with request details."),
  MESSAGE_DELIVERY_FAILURE(18402, "Message Delivery Failure"),
  API_SCHEMA_NOT_PER_STANDARD(18406, "API schema not per standard."),
  RETURN_ADDRESS_NOT_FOUND(18407, "One return address is mandatory."),
  BULK_REQUEST_TYPE_CONDITION_FAIL(18408,
      "If the request category is 'BulkDataOnly' or 'BulkPrintReady', then the RequestDetail must contain the BulkRequestDetail element only."),
  TRANSACTIONAL_REQUEST_TYPE_CONDITION_FAIL(18409,
      "If request category is 'TransactionalInlineDataOnly' or 'TransactionalExternalDataOnly' or 'TransactionalInlinePrintReady' or 'TransactionalExternalPrintReady' then RequestDetail must contain the TransactionalRequestDetail element only."),
  TEMPLATE_INFO_MISSING(18410, "Template information is missing."),
  TEMPLATE_ID_NOT_FOUND(18411, " Template ID is required for each template."),
  RECIPIENT_ID_MISSING(18412, "Recipient ID is missing."),
  ID_QUALIFIER_MISSING(18413, "ID Qualifier is missing."),
  NO_FULFILLMENT_MATERIAL_DATA_PAYLOAD(18414,
      "No fulfillment material data payload defined."),
  INVALID_DELIVERY_METHOD(18415, "Invalid delivery method."),
  FAX_NUMBER_SHOULD_BE_FILLED(18416,
      "If delivery channel selected was 'fax', the fax number should be filled-up."),
  EMAIL_ADDRESS_SHOULD_BE_FILLED(18417,
      "If delivery channel selected was 'email', the email address should be filled-up."),
  INVALID_EMAIL(18418, "Given email address is not well formed."),
  DUPLICATE_FULFILLMENT_REQUEST(18419, "Duplicate fulfillment request."),
  FULFILLMENT_NOT_FOUND(18420, "Fulfillment request not found."),
  ID_QUALIFIER_NOT_FOUND(18421, "ID Qualifier is not found."),
  MAILING_ADDRESS_MANDATORY(18422, "Mailing address is mandatory."),
  SOURCE_ID_APPLICATION_ID_MISSING(18500, "SourceID (ApplicationID) is missing"),
  //REQUEST_TYPE_MISSING(18501, "Request type is missing."),
  DATA_SEGMENT_MISSING(18502, "Data Segment(FundingType) is missing"),
  ORGANIZATION_MISSING(18503, "Organization is missing"),
  ROUTE_MISSING(18504, "Route is missing"),
  POLICY_MISSING(18505, "Policy is missing"),
  REDELIVERY_ID_MISSING(18506, "ReDeliveryID is missing"),
  DUPLICATE_REDELIVERY_REQUEST(18507, "Duplicate ReDelivery request"),
  DOCUMENT_ID_MISSING(18508, "DocumentID is missing"),
  DOCUMENT_CLASS_MISSING(18509, "DocumentClass is missing"),
  DELIVERY_MEDIUM_MISSING(18510, "DeliveryMedium is missing"),
  DELIVERY_MEDIUM_INVALID(18511, "DeliveryMedium Should be 'Mailed','Fax' Or 'Emailed'."),
  FIRST_NAME_MISSING_IN_DELIVERY_ADRESS(18512, "FirstName is missing in Delivery Address"),
  LAST_NAME_MISSING_IN_DELIVERY_ADRESS(18513, "LastName is missing in Delivery Address"),
  ADDRESS1_MISSING_IN_DELIVERY_ADRESS(18514, "Address1 is missing in Delivery Address"),
  CITY_MISSING_IN_DELIVERY_ADRESS(18515, "City is missing in Delivery Address"),
  STATE_MISSING_IN_DELIVERY_ADRESS(18516, "State is missing in Delivery Address"),
  ZIP_MISSING_IN_DELIVERY_ADRESS(18517, "Zip is missing in Delivery Address"),
  ADDRESS_MISSING(18518, "Address is missing"),
  ADDRESS1_MISSING_IN_INTERNATIONAL_DELIVERY_ADRESS(18519,
      "Address1 is missing in International Delivery Address"),
  CITY_MISSING_IN_INTERNATIONAL_DELIVERY_ADRESS(18520,
      "City is missing in International Delivery Address"),
  PROVINCE_MISSING_IN_INTERNATIONAL_DELIVERY_ADRESS(18521,
      "Province is missing in International Delivery Address"),
  POSTAL_CODE_MISSING_IN_INTERNATIONAL_DELIVERY_ADRESS(18522,
      "PostalCode is missing in International Delivery Address"),
  COUNTRY_MISSING_IN_INTERNATIONAL_DELIVERY_ADRESS(18523,
      "Country is missing in International Delivery Address"),
  FAX_NUMBER_MISSING(18524, "Fax Number is missing"),
  EMAIL_ADDRESS_MISSING(18525, "Email Address is missing"),
  RECIPIENT_TYPE_MISSING(18529, "RecipientType is missing"),
  DENIED_ACCESS_TO_DOCUMENTUM(18534, "Denied access to Documentum"),
  ERROR_MERGING_DOCUMENTS(18535, "Error merging documents"),
  ERROR_CREATING_AFP_FILES(18536, "Error creating AFP files"),
  ERROR_CREATING_PROCESS_REQUEST(18537, "Error creating ProcessFFRequests"),
  ERROR_SFTP_LANDING_ZONE(18538, "Error SFTP'ing to Landing Zone"),
  HTTP_CLIENT_ERROR_EXCEPTION(18541, "HttpClientErrorException"),
  PERMISSION_DENIED_EXCEPTION(18542, "PermissionDeniedException"),
  CLASS_NOT_FOUND_EXCEPTION(18543, "ClassNotFoundException"),
  BEAN_CREATION_EXCEPTION(18544, "BeanCreationException"),
  BEAN_INSTANTIATION_EXCEPTION(18545, "BeanInstantiationException"),
  HTTP_MESSAGE_CONVERSION_EXCEPTION(18546, "HttpMessageConversionException"),
  NO_SUCH_BEAN_DEFINITION_EXCEPTION(18547, "NoSuchBeanDefinitionException"),
  REMOTE_INVOCATION_FAILURE(18548, "RemoteInvocationFailureException"),
  END_POINT_NOT_FOUND_EXCEPTION(18549, "EndPointNotFoundException"),
  SOAP_FAULT_EXCEPTION(18550, "SoapFaultException"),
  ILLEGAL_ARGUMENT_EXCEPTION(18551, "IllegalArgumentException"),
  MESSAGE_DELIVERY_EXCEPTION(18552, "MessageDeliveryException"),
  MESSAGING_EXCEPTION(18553, "MessagingException"),
  REQUEST_TYPE_REDELIVERY(18600, "RequestType is Invalid. Valid value is 'ReDelivery'."),
  RECIPIENT_INFO_MISSING(18071, "Recipient information is missing."),
  DISPATCHED_DATE_MISSING(18072, "Dispatched date is missing"),
  REQUEST_DETAIL_MISSING(18073, "Request Detail is missing."),
  REQUEST_TRAILER_MISSING(18074, "Request Trailer is missing."),
  POST_BULK_ITEM_STATUS_MISSING(18075, "PostBulkItemStatus is missing."),
  PERSON_AND_ORGANIZATION_BOTH_MISSING(18076, "Both Person and Organization are missing"),
  DATA_FIELD_MISSING(18077, "Data Field in the request is missing"),
  CONTENT_FORMAT_MISSING(18078, "Content format inside 'data' field in the request is missing"),
  NO_FILE_TARSNFER_INSTRUCTION(18070, "No file transfer instructions found"),

  //Below error codes are not provided
  BUSINESS_SEGMENT_NOT_FOUND(18601, "Business Segment is not found."),
  MARKET_SEGMENT_NOT_FOUND(18602, "Market Segment is not found."),
  DELIVERY_MEDIUM_TWO_INVALID(18603, "DeliveryMedium Should be 'Mailed','Fax', 'Emailed' or null.");

  @Getter
  private final int code;
  @Getter
  private final String message;

  ErrorCode(int code, String message) {
    this.code = code;
    this.message = message;
  }

  @Override
  public String toString() {
    return code + " : " + message;
  }
}
